import React from 'react';
import {
    PencilRuler,
    Merge,
    Scissors,
    Zap,
    Wrench,
    ImagePlus,
    PenTool,
    Crop,
    Ungroup,
    Files,
    Trash2,
    Bookmark,
    List,
    ListOrdered,
    Droplets,
    Pilcrow,
    Contrast,
    Palette,
    Type,
    Stamp,
    Eraser,
    SquarePen,
    FileInput,
    FileMinus2,
    Images,
    Image as ImageIcon,
    Smartphone,
    Layers,
    FilePen,
    FileCode,
    FileImage,
    FileText,
    ScanText,
    Shuffle,
    Paperclip,
    Download,
    FileEdit,
    Columns,
    FilePlus2,
    ArrowDownZA,
    RotateCw,
    LayoutGrid,
    UnfoldVertical,
    Info,
    FileCog,
    StretchHorizontal,
    GitCompare,
    NotepadTextDashed,
    Ruler,
    Gauge,
    Unlink,
    Lock,
    ShieldCheck,
    Brush,
    Key,
    FileKey,
    FileLock,
    Sparkles,
    LucideIcon,
    // File format icons
    FileSpreadsheet,
    Presentation,
    FileBox,
    FileType2,
    BookOpen,
    BookMarked,
    RefreshCcw,
    ImageDown,
    Table,
    LayoutDashboard,
    TabletSmartphone,
    FileScan,
    BookText,
    Tag,
    Clock,
    SearchX,
    Unlock,
    FileX,
    ScanLine,
    Grid2X2,
    Mail,
    BookImage,
    Archive,
    Link2,
    ShieldAlert,
    Workflow,
    SunMoon,
    LockKeyhole,
    Columns2,
    Expand,
    Pencil,
    CheckSquare
} from 'lucide-react';

import { TOOL_VECTOR_ICONS } from '@/components/icons/tool-icons';

export const ICON_MAP: Record<string, React.ComponentType<any>> = {
    'pencil-ruler': PencilRuler,
    'combine': Merge,
    'merge': Merge,
    'scissors': Scissors,
    'zap': Zap,
    'pocket-knife': Wrench,
    'image-up': ImagePlus,
    'pen-tool': PenTool,
    'crop': Crop,
    'ungroup': Ungroup,
    'files': Files,
    'trash-2': Trash2,
    'bookmark': Bookmark,
    'list': List,
    'list-ordered': ListOrdered,
    'droplets': Droplets,
    'pilcrow': Pilcrow,
    'contrast': Contrast,
    'palette': Palette,
    'type': Type,
    'stamp': Stamp,
    'eraser': Eraser,
    'square-pen': SquarePen,
    'file-input': FileInput,
    'file-minus-2': FileMinus2,
    'images': Images,
    'image': ImageIcon,
    'smartphone': Smartphone,
    'layers': Layers,
    'file-pen': FilePen,
    'file-code': FileCode,
    'file-image': FileImage,
    'file-text': FileText,
    'scan-text': ScanText,
    'shuffle': Shuffle,
    'paperclip': Paperclip,
    'download': Download,
    'file-edit': FileEdit,
    'table-columns-split': Columns,
    'file-plus-2': FilePlus2,
    'arrow-down-z-a': ArrowDownZA,
    'rotate-cw': RotateCw,
    'layout-grid': LayoutGrid,
    'unfold-vertical': UnfoldVertical,
    'info': Info,
    'file-cog': FileCog,
    'stretch-horizontal': StretchHorizontal,
    'git-compare': GitCompare,
    'notepad-text-dashed': NotepadTextDashed,
    'ruler-dimension-line': Ruler,
    'ruler': Ruler,
    'gauge': Gauge,
    'unlink': Unlink,
    'wrench': Wrench,
    'lock': Lock,
    'brush-cleaning': Brush,
    'shield-check': ShieldCheck,
    'key': Key,
    'file-key': FileKey,
    'file-lock': FileLock,
    'file-spreadsheet': FileSpreadsheet,
    'presentation': Presentation,
    'file-box': FileBox,
    'file-type': FileType2,
    'book-open': BookOpen,
    'book-marked': BookMarked,
    'refresh-ccw': RefreshCcw,
    'image-down': ImageDown,
    'table': Table,
    'layout-dashboard': LayoutDashboard,
    'tablet-smartphone': TabletSmartphone,
    'sparkles': Sparkles,
    'file-scan': FileScan,
    'book-text': BookText,
    'tag': Tag,
    'clock': Clock,
    'search-x': SearchX,
    'unlock': Unlock,
    'file-x': FileX,
    'scan-line': ScanLine,
    'grid-2x2': Grid2X2,
    'mail': Mail,
    'book-image': BookImage,
    'archive': Archive,
    'link-2': Link2,
    'shield-alert': ShieldAlert,
    'workflow': Workflow,
    'sun-moon': SunMoon,
    'lock-keyhole': LockKeyhole,
    'columns-2': Columns2,
    'expand': Expand,
    'pencil': Pencil,
    'check-square': CheckSquare,
    // Add all specialized vector icons to the map
    ...TOOL_VECTOR_ICONS
};

/**
 * Get icon component for a tool.
 * Returns modern minimalist vector icon if available, otherwise falls back to Lucide or FileText.
 */
export const getToolIcon = (iconName: string): React.ComponentType<any> => {
    if (TOOL_VECTOR_ICONS[iconName]) {
        return TOOL_VECTOR_ICONS[iconName];
    }
    return ICON_MAP[iconName] || FileText;
};
